---
abstract: 'collect openafs metrics'
author:
  - 'Fabien Wernli, C<< <wernli ate in2p3.fr> >>'
  - 'Fabien Wernli <wernli ate in2p3.fr>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Collectd-Plugins-OpenAFS
no_index:
  directory:
    - inc
    - share
    - t
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1006
